language: python
python:
    - "2.6"
    - "2.7"

install:
    - pip install clustershell
    - pip install coverage
    - pip install codecov

before_script:
    # Allow us to SSH passwordless to local host
    - ssh-keygen -f ~/.ssh/id_rsa -N ""
    - cp ~/.ssh/{id_rsa.pub,authorized_keys}
    # Avoid ssh "known hosts" warnings
    - printf '%s\n    %s\n    %s\n' 'Host *' 'StrictHostKeyChecking no' 'LogLevel ERROR' >> ~/.ssh/config
    # Default empty group sources for clustershell
    - mkdir -p ~/.local/etc/clustershell
    - "echo -e '[Main]\\ndefault: local\\n[local]\\nmap: echo' > ~/.local/etc/clustershell/groups.conf"

script:
    - export PYTHONPATH=$PWD/lib/; nosetests --exe --all-modules -w tests --with-coverage

# Push the results back to codecov
after_success:
- codecov
